Remove superfluous = from Doxygen PREDEFINE
Doxygen 1.8.17 reporst this as error:

   error: Illegal PREDEFINED format '=', no define name specified

It seems Doxygen output is not affected by removal of the `=` sign.
Closes #678